apiVersion: nais.io/v1alpha1
kind: Application
metadata:
  name: portalserver
  namespace: navdig
  labels:
    team: navdig
spec:
  env:
    - name: FRONTEND_LOCATION
      value: https://status.dev.nav.no
  replicas:
    min: 1
    max: 1
  secureLogs:
    enabled: true
  image: {{ image }}
  port: 3005
  ingresses:
    - https://status-api.dev.nav.no
  gcp:
    sqlInstances:
      - name: navstatus
        type: POSTGRES_12
        highAvailability: true
        tier: db-custom-2-3840
        databases:
          - name: navstatus
            envVarPrefix: DB
