apiVersion: nais.io/v1alpha1
kind: Application
metadata:
  name: portalserver
  namespace: navdig
  labels:
    team: navdig
spec:
  envFrom:
    - secret: nav-status-db-pass
  env:
    - name: FRONTEND_LOCATION
      value: https://portal.labs.nais.io
  secureLogs:
    enabled: true
  image: {{ image }}
  port: 3005
  ingresses:
    - https://status.nav.no/sp/backend
  gcp:
    sqlInstances:
      - name: navstatus
        type: POSTGRES_12
        highAvailability: true
        tier: db-custom-2-3840
        databases:
          - name: navstatus
            envVarPrefix: DB
  azure:
    application:
      enabled: true
      # optional, enum of {trygdeetaten.no, nav.no}
      # defaults to trygdeetaten.no in dev-* clusters, nav.no in production
      tenant: nav.no
      # optional
      replyURLs:
      - "https://status.nav.no/sp/rest/oauth2/callback"
      - "https://status.nav.no/sp/rest/Dashboard/Privatperson"
      claims:
        extra:
          - "NAVident"
          - "azp_name"
      # optional, defaults shown
      singlePageApplication: false