apiVersion: nais.io/v1alpha1
kind: Application
metadata:
  name: portalserver
  namespace: navdig
  labels:
    team: navdig
spec:
  envFrom:
    - secret: nav-status-db-pass
  secureLogs:
    enabled: true
  image: {{ image }}
  port: 3001
  ingresses:
    - https://digitalstatus2.ekstern.dev.nav.no
  #image: ghcr.io/navikt/myapplication:417dcaa2c839b9da72e0189e2cfdd4e90e9cc6fd
  #       ^--- interpolated from the ${{ env.docker_image }} variable in the action