openapi: 3.0.3
info:
  description: Documentation Nav portal REST API
  version: '0.1'
  title: Nav REST API
tags:
  - name: area-controller
    description: area Controller
servers:
  - url: /rest
paths:
  /testAreas:
    get:
      tags:
        - area-controller
      summary: area
      operationId: areas
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Area'
        '401':
          description: Unauthorized
          content: {}
        '403':
          description: Forbidden
          content: {}
        '404':
          description: Not Found
          content: {}
      deprecated: false
  /testStatus:
    get:
      tags:
        - status
      summary: Status og hendelser
      operationId: status
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/StatusAndIncidents'
        '401':
          description: Unauthorized
          content: {}
        '403':
          description: Forbidden
          content: {}
        '404':
          description: Not Found
          content: {}
      deprecated: false
  /adminAreas:
    get:
      tags:
        - AdminArea
      summary: Mulige områder tjenester kan legges i
      operationId: AdminArea
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/AdminArea'
        '401':
          description: Unauthorized
          content: { }
        '403':
          description: Forbidden
          content: { }
        '404':
          description: Not Found
          content: { }
      deprecated: false
    post:
      summary: Legg til ett nytt område
      requestBody:
        description:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/AdminArea'
          text/plain:
            schema:
              type: string
      responses:
        '201':
          description: Created
        '403':
          description: Forbidden
          content: { }
        '404':
          description: Not Found
          content: { }

components:
  schemas:
    StatusAndIncidents:
      title: Area
      type: object
      properties:
        name:
          type: string
        status:
          $ref: '#/components/schemas/SandIelement'
    SandIelement:
      type: string
    Area:
      title: Area
      type: object
      properties:
        name:
          type: string
        status:
          $ref: '#/components/schemas/Status'
        services:
          type: array
          items:
            $ref: '#/components/schemas/Service'
    AdminArea:
      title: Area
      type: object
      properties:
        name:
          type: string
        Id:
          type: string
        beskrivelse:
          type: string
        rangering:
          type: integer
    Service:
      title: Service
      type: object
      properties:
        name:
          type: string
        status:
          $ref: '#/components/schemas/Status'

    Status:
      type: string
      enum:
        - OK
        - ISSUE
        - DOWN

