openapi: 3.0.3
info:
  description: Documentation Nav portal REST API
  version: '0.1'
  title: Nav REST API
servers:
  - url: /rest
paths:
  /tiles:
    get:
      tags:
        - Tiles
      summary: Tiles
      operationId: Tiles
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Tile'
        '401':
          description: Unauthorized
          content: {}
        '403':
          description: Forbidden
          content: {}
        '404':
          description: Not Found
          content: {}
      deprecated: false
  /testStatus:
    get:
      tags:
        - status
      summary: Status og hendelser
      operationId: status
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/StatusAndIncidents'
        '401':
          description: Unauthorized
          content: {}
        '403':
          description: Forbidden
          content: {}
        '404':
          description: Not Found
          content: {}
      deprecated: false
  /Areas:
    get:
      tags:
        - Area
      summary: Mulige områder tjenester kan legges i
      operationId: Area
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Area'
        '401':
          description: Unauthorized
          content: { }
        '403':
          description: Forbidden
          content: { }
        '404':
          description: Not Found
          content: { }
      deprecated: false
    post:
      tags:
        - Area
      summary: Legg til ett nytt område
      requestBody:
        description: Legg til ett nytt område
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Area'
          text/plain:
            schema:
              type: string
      responses:
        '201':
          description: Created
        '403':
          description: Forbidden
          content: { }
        '404':
          description: Not Found
          content: { }

components:
  schemas:
    StatusAndIncidents:
      title: Area
      type: object
      properties:
        name:
          type: string
        status:
          $ref: '#/components/schemas/SandIelement'
    SandIelement:
      type: string
    Tile:
      title: Tile
      type: object
      properties:
        area:
          $ref: '#/components/schemas/Area'
        status:
          $ref: '#/components/schemas/Status'
        services:
          type: array
          items:
            $ref: '#/components/schemas/Service'
    Dashboard:
      title: Dashboard
      type: object
      properties:
        name:
          type: string
        id:
          type: string
        areas:
          type: array
          items:
            $ref: '#/components/schemas/Area'
    Area:
      title: Area
      type: object
      properties:
        name:
          type: string
        id:
          type: string
        beskrivelse:
          type: string
        ikon:
          type: string
        rangering:
          type: integer
    Service:
      title: Service
      type: object
      properties:
        name:
          type: string
        status:
          $ref: '#/components/schemas/Status'

    Status:
      type: string
      enum:
        - OK
        - ISSUE
        - DOWN

