openapi: 3.0.3
info:
  description: Documentation Nav portal REST API
  version: '0.1'
  title: Nav REST API
tags:
  - name: area-controller
    description: area Controller
servers:
  - url: /rest/v0.1
paths:
  /testAreas:
    get:
      tags:
        - area-controller
      summary: area
      operationId: doesThisDoAnyTHnig
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Area'
        '401':
          description: Unauthorized
          content: {}
        '403':
          description: Forbidden
          content: {}
        '404':
          description: Not Found
          content: {}
      deprecated: false
components:
  schemas:
    Area:
      title: Area
      type: object
      properties:
        name:
          type: string
        status:
          type: integer
          format: int32
        services:
          type: array
          items:
            $ref: '#/components/schemas/Service'
    Service:
      title: Service
      type: object
      properties:
        name:
          type: string
        status:
          type: string
          enum:
            - OK
            - ISSUE
            - DOWN

